### ISSUE TITLE
Nalkuta eri kentistä luettelointipohjan mukaan

### ISSUE THREAD

**Issue by paxed** [KohaSuomi/koha-plugin-nalkutin#1]
Lumpeessa haluisivat että nalkutin ei valittaisi kuin parista tietystä kentästä (245a, 942c), jos luettelointipohja on TI (tilauspohja)

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä: Viedään Indeksointi- ja tiedonhakuryhmään päätettäväksi.

Asiantuntijaryhmän huomioita:
* Nalkutin muutettaisiin sellaiseksi, että jokaiselle/halutuille kuvailupohjalle voidaan määrittää omat säännöt, joiden mukaan nalkutetaan.

**Comment by AnneliO** [comment]
Indeksointi- ja tiedonhakuryhmä 23.10.2024: Tälle toiminnolle ei ole tarvetta. Ei toteuteta.
